### ISSUE TITLE
Unclear code

### ISSUE THREAD

**Issue by MOZGIII** [ory/hydra-consent-app-go#11]
Consider this code:

https://github.com/ory/hydra-consent-app-go/blob/29e5a465dcb9bc8d3d75f9bea04d20b0c0984ae2/main.go#L66-L73

At line 67 `client.GetOAuth2Config()` is called and the value is assigned to `config` var.
At line 71 `client.GetOAuth2Config()` is called again, and the `config` var in not used.

Why is that? Is it a bug, and `client` var should be used on line 71?

**Comment by aeneasr** [comment]
It overrides the values in the pointer, config is just a shorthand for `client.GetOAuth2Config()`, so it's not an issue.

**Comment by MOZGIII** [comment]
Any reason why it's not properly setup on initialization and is written like this? This code is actually not thread-safe: if values are updated via a pointer, multiple goroutines can potentially race over setting those values. Go has happens before semantics if the event ordering is clearly defined in the code (i.e. via channels), and in this case it's not properly specified.

**Comment by aeneasr** [comment]
Yeah that's a nice catch. I guess these lines could be moved to [here](https://github.com/ory/hydra-consent-app-go/blob/29e5a465dcb9bc8d3d75f9bea04d20b0c0984ae2/main.go#L46)!

**Comment by MOZGIII** [comment]
Yep. Also, updating pointer values doesn't seems like a legit thing to do for me. This is very awkward. Isn't there a cleaner API to do it?

**Comment by aeneasr** [comment]
> Yep. Also, updating pointer values doesn't seems like a legit thing to do for me.

Yeah, the SDK API is a bit strange here. We should probably not use the hydra SDK at all for initiating the authorization url / exhcanging the access code, but a dedicated variable. This example isn't that great anyways because it combines all of the endpoints in one code base, which confuses a lot of beginners.

Actually, I wanted to deprecate it with the 1.0 release, because more people are familiar with NodeJS than Go and it's less work to maintain one project.

**Comment by MOZGIII** [comment]
I found this particular sample very helpful, and I opened it right after looking at JavaScript version. JavaScript examples were too complicated to grasp for me (a lot of confusing indirection, like `resolvers` thingy). With Go it was much simpler to understand how to actually use the API.

I'm not saying that I'm against deprecation, but just sharing my experience as a beginner with the API. I feel like NodeJS example should be made trivial, with all "boring" stuff exposed (in contrary to be hidden by some non-essential abstractions). Hope this input is useful.

**Comment by aeneasr** [comment]
Yeah, this makes a ton of sense - the generated Node SDK is terrible and almost anything has to be solved by hand - requiring tons of promises and stuff. If this here is indeed to be deprecated, the Node example will be polished and hopefully easier to understand.

**Comment by MOZGIII** [comment]
> Actually, I wanted to deprecate it with the 1.0 release, because more people are familiar with NodeJS than Go and it's less work to maintain one project.

Just to make sure: it was this repo that you was talking about, and not hydra Go SDK, right? Can I build stuff using Go SDK and rely on it being supported in the future?

**Comment by aeneasr** [comment]
Yes, but please be aware that we auto-generate the Go SDK using [`swagger-codegen`](https://github.com/swagger-api/swagger-codegen) which in turn has (unfortunately) terrible BC support. There will be at least one major update to the Go SDK codebase which will land in [swagger-codegen 2.4.0](https://github.com/swagger-api/swagger-codegen/pull/7987) and is crucial to improving the developer experience of the Go SDK.
