### ISSUE TITLE
misleading error message and env vars

### ISSUE THREAD

**Issue by androbi-com** [ory/hydra-consent-app-go#12]
During setup of my hydra I noted the following little problems in the current go version of the consent app. I see that the authors are thinking about deprecating the go version, but maybe these observations might be helpful for the ones that want to use it.

1) When an error is redirected from hydra to the consent app, (see [oauth2/handler.go]( https://github.com/ory/hydra/blob/master/oauth2/handler.go#L585)) the parameter "consent" is not set, but "error" and "error_description". However, the consent app shows the message "Consent endpoint was called without a consent request id", which is correct, but it obfuscates what has happened inside hydra (i.e. "unkown client"). I included the following lines at the beginning of [consentHandler](https://github.com/ory/hydra-consent-app-go/blob/master/main.go#L77):

```
// check if an error has been send in from hydra
errorCode := r.URL.Query().Get("error")
if errorCode != "" {
    errorDescr := r.URL.Query().Get("error_description")
    http.Error(w,errors.New("Error: " + errorCode + ": " + errorDescr).Error(),http.StatusBadRequest)
        return
}
```
2) Also, for this example to work with the docker instructions in the docs, the env variable HYDRA_CLUSTER_URL should be renamed to HYDRA_URL in [main.go](https://github.com/ory/hydra-consent-app-go/blob/master/main.go#L40). 

3) If you play around with the ports, it comes in handy to obtain the consent [callback url](https://github.com/ory/hydra-consent-app-go/blob/master/main.go#L68) from an environment variable, so it can be set from the command line:

   `  config.RedirectURL = env.Getenv("CONSENT_CALLBACK", "http://localhost:4445/callback")`

**Comment by aeneasr** [comment]
Thank you for these observations! The app will be indeed deprecated, but it might sitll be helpful for others!
