### ISSUE TITLE
Error installing the app with incompatibilities

### ISSUE THREAD

**Issue by sredxny** [ory/hydra-consent-app-go#2]
HI, I just installed it in my envoriment running Go 1.8. But I get this error:

`src/github.com/ory/hydra/pkg/fosite_storer.go:14: undefined: oauth2.AuthorizeCodeGrantStorage`

it seems like it's not a valid command anymore, how should I replace it?

**Comment by aeneasr** [comment]
please use glide as advised in the readme

**Comment by jdeats76** [comment]
I'm able to install all dependencies with $go get ... with the exception of github.com/ory-am/hydra/sdk 
The repo at github.com/ory-am has been moved and the new location is empty. Attempting to point to github.com/ory/hydra/sdk does not work so this is clearly a different SDK or the referenced SDK by this consent demo is outdated.

**Comment by aeneasr** [comment]
`github.com/ory-am/hydra` points to `github.com/ory/hydra`. However, there is clearly something wrong with the set up, but I will not be able to fix this in the next week as my schedule is really busy atm. Thank you for reporting!

**Comment by aeneasr** [comment]
Should be resolved now!
